name: psql-fulltext-search

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres16_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./examples:/examples
      - ./scripts/init-database.sql:/docker-entrypoint-initdb.d/1-init-database.sql
      - ./scripts/add-tsvector.sql:/docker-entrypoint-initdb.d/2-init-database.sql
      - ./scripts/populate-database.sh:/docker-entrypoint-initdb.d/3-init-database.sh
    networks:
      - postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: unless-stopped
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_DEFAULT_EMAIL: admin@admin.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./config/servers.json:/pgadmin4/servers.json
    networks:
      - postgres
    ports:
      - "5050:80"
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  local_pgdata:
  pgadmin-data:
